//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjemploWebService.PruebasWeb
{
    public partial class _Default
    {
        protected global::System.Web.UI.WebControls.TextBox txtServicioUrl;

        protected global::System.Web.UI.WebControls.Button btnCargarPersonas;

        protected global::System.Web.UI.WebControls.Button btnCargarRoles;

        protected global::System.Web.UI.WebControls.Label lblMensaje;

        protected global::System.Web.UI.WebControls.TextBox txtPersonaId;

        protected global::System.Web.UI.WebControls.TextBox txtNombre;

        protected global::System.Web.UI.WebControls.TextBox txtTipo;

        protected global::System.Web.UI.WebControls.TextBox txtGender;

        protected global::System.Web.UI.WebControls.TextBox txtPassword;

        protected global::System.Web.UI.WebControls.Button btnBuscar;

        protected global::System.Web.UI.WebControls.Button btnGuardar;

        protected global::System.Web.UI.WebControls.Button btnEliminar;

        protected global::System.Web.UI.WebControls.Button btnLimpiar;

        protected global::System.Web.UI.WebControls.GridView gvPersonas;

        protected global::System.Web.UI.WebControls.Button btnCargarTelefonos;

        protected global::System.Web.UI.WebControls.GridView gvRoles;

        protected global::System.Web.UI.WebControls.GridView gvTelefonos;
    }
}
